udpdate from dat dz

diff --git a/pomodoro/tomatoshell/bin/tomatoshell b/pomodoro/tomatoshell/bin/tomatoshell
--- a/pomodoro/tomatoshell/bin/tomatoshell
+++ b/pomodoro/tomatoshell/bin/tomatoshell
@@ -17,24 +17,21 @@
 
 HELP="
 -r,     prints total hours spent using tomatoshell and exits
--t,     time for every session in minutes [default:60 minutes]
--d,     delay between sessions in minutes [default:10 minutes]
--n,     total sessions [default:1]
+-t,     time for every session in minutes [default:25 minutes]
+-d,     delay between sessions in minutes [default:5 minutes]
+-n,     total sessions [default:3]
 -f,     figlet on
 -p,     pause key to use during countdown [default:none]
 -h,     shows this"
 
 # defaults
-TIME=60
+TIME=50
 DELAY=10
-SESSIONS=1
+SESSIONS=4
 
 FIGLET=false
-ALARM="$HOME/tomatoshell/etc/alarm.wav"
-MUSIC="$HOME/Dropbox/My Hero Academia OST - You Say Run + Jet Set Run (You Say Run v2).mp3"
-START_TIME_MUSIC=0 # 124 or 0
-TIME_PLAY_MUSIC=20   # p for kill music
-LOG="$HOME/tomatoshell/tomatoshell_log.csv"
+ALARM="/home/dat/dotfiles/pomodoro/tomatoshell/etc/alarm.wav"
+LOG="/home/dat/dotfiles/pomodoro/tomatoshell/checkTime.csv"
 AUDIO_PLAYER=3
 PAUSE_KEY='p'
 
@@ -45,10 +42,12 @@ YELLOW="\033[0;33m"
 CYAN="\033[0;34m"
 FIN="\033[0m"
 
+
 write_to_log() {
     date_f=$(date +"%Y-%m-%d")
     echo "$date_f,$SESSIONS,$TIME" >> "$LOG"
 }
+
 
 total_hours_used() {
     printf "$YELLOW Total time spent focused: $FIN"
@@ -56,134 +55,120 @@ total_hours_used() {
     printf " 🍅🤓\n"
 }
 
+
+# TODO: add option for xdg-open
 find_sound_system() {
-    if command -v mplayer &> /dev/null; then
-        AUDIO_PLAYER=mplayer
-    elif command -v paplay &> /dev/null; then
+    # added support for pipewire audio player, tested on pop-os (debian)
+    # since, its packed with the OS.
+    if command -v mpv &> /dev/null
+    then
+        AUDIO_PLAYER=mpv
+
+    elif command -v paplay &> /dev/null
+    then
         AUDIO_PLAYER=paplay
-    elif command -v pw-play &> /dev/null; then
+    # set AUDIO_PLAYER as pw-play 
+    elif command -v pw-play &> /dev/null
+    then
         AUDIO_PLAYER=pw-play
-    elif command -v aplay &> /dev/null; then
+
+    elif command -v aplay &> /dev/null
+    then
         AUDIO_PLAYER=aplay
+
     else
         AUDIO_PLAYER=0
     fi
 }
 
+
 play_alarm() {
+    # when session is finished, start the alarm
     printf "Press 's' to stop alarm"
     [ $1 -eq -1 ] && echo " and start next session" || echo ""
 
     process_name="tomatoshell_alarm"
 
-    while :; do
-        if ! [ -e /proc/"$(pidof "$process_name")"/status ]; then
+    while :
+    do
+        # play alarm sound indefinetely until the 's' key is pressed
+
+        if ! [ -e /proc/"$(pidof "$process_name")"/status ]
+        then
+            # janky :/
             bash -c "exec -a $process_name $AUDIO_PLAYER $ALARM &>/dev/null" &
         else
             read -t 0.01 -r -s -n 1
             [[ $REPLY == 's' ]] && pkill -f "$process_name" && break
         fi
+    
     done
 }
 
-play_music() {
-    process_name="tomatoshell_music"
-
-    if ! [ -e /proc/"$(pidof "$process_name")"/status ]; then
-        bash -c "exec -a $process_name $AUDIO_PLAYER -ss $START_TIME_MUSIC -endpos $TIME_PLAY_MUSIC '$MUSIC' &>/dev/null" &
-    fi
-}
-
-display_centered_figlet() {
-    text="$1"
-    cols=$(tput cols)
-    while IFS= read -r line; do
-        line_length=${#line}
-        padding=$(( (cols - line_length) / 2 ))
-        printf "%*s%s\n" $padding "" "$line"
-    done < <(figlet -f slant "$text")
-}
 
 display_countdown() {
     start=$1
-    session_number=$2
-    print_offset=10
 
-    while [ "$start" -ge "$(date +%s)" ]; do
-        remaining=$(date -u --date @$((start - $(date +%s))) +%M:%S)
-
-        clear
-
-        lines=$(tput lines)
-        cols=$(tput cols)
-        vertical_padding=$((lines / 2 - 6))
-
-        for ((i=0; i<vertical_padding; i++)); do echo ""; done
-
-        if $FIGLET; then
-            if [[ $session_number -ne -1 ]]; then
-                display_centered_figlet "STAY HARD"
-                session_str="Session $session_number/$SESSIONS"
-                padding=$(( (cols + ${#session_str}) / 2 ))
-                printf "%*s\n" $padding "$session_str"
-            else
-                display_centered_figlet "BREAK TIME"
-            fi
-            echo "$remaining" | figlet | while IFS= read -r line; do
-                padding=$(( (cols - ${#line}) / 2 ))
-                printf "%*s%s\n" "$padding" "" "$line"
-            done
-        else
-            msg="🍅Time left of session $session_number/$SESSIONS:🍅"
-            [ $session_number -eq -1 ] && msg="🍅Time left of break:🍅"
-            printf "%*s\n" $(((${#msg}+$cols+print_offset)/2)) "$msg"
-            printf "%*s\r" $(((${#remaining}+$cols+print_offset)/2)) "$CYAN⏳ $YELLOW $remaining$FIN  🍅"
-        fi
+    # yeahhhh I don̈́'t know what's going on here either
+    while [ "$start" -ge "$(date +%s)" ]
+    do
+        # due to the rendering of emoji's, the text needs to be offset to appear at the center.
+        # sleeping for one second between each print to stdout uses less cpu power, but will
+        # make the countdown have a discrepency of 1s which is negligable.
+        print_offset=10
+        $FIGLET && clear && printf "%*s\n" $(((${#msg}+$COLUMNS+$print_offset)/2)) "$msg" \
+        && echo -ne "$(date -u --date @$((start - $(date +%s))) +%M:%S)\r" | figlet -c -t ||
+        echo -ne "$CYAN\Uf061 $YELLOW $(date -u --date @$((start - $(date +%s))) +%M:%S)$FIN  🍅\r"
 
         read -t 1 -r -s -N 1 && {
-            if [[ $REPLY == 'q' ]]; then
-                pkill -f "tomatoshell_music"
-                exit_p
-            elif [[ $REPLY == 's' ]]; then
-                pkill -f "tomatoshell_music"
-                break
-            elif [[ $REPLY == 'p' ]]; then
-                pkill -f "tomatoshell_music"
-                echo -e "\n$YELLOW Paused... Press p to resume $FIN"
-                local pause_time=$(date +%s)
-                while :; do
-                    read -r -s -N 1 key
-                    if [[ $REPLY == 'p' ]]; then
-                        local resume_time=$(date +%s)
-                        local paused_duration=$((resume_time - pause_time))
-                        start=$((start + paused_duration))
-                        echo -e "$GREEN Resuming...$FIN"
-                        break
-                    fi
-                done
-            fi
+        if [[ $REPLY == 'q' ]]; then
+            exit_p
+        elif [[ $REPLY == 's' ]]; then
+            break
+        elif [[ $REPLY == 'p' ]]; then
+            echo -e "\n$YELLOW Paused... Press p to resume $FIN"
+            local pause_time=$(date +%s)
+            while : ; 
+            do
+                read -r -s -N 1 key
+                if [[ $REPLY == 'p' ]]; then
+                 local resume_time=$(date +%s)  # Get the current time after resuming
+                        local paused_duration=$((resume_time - pause_time))  # Calculate the duration of the pause
+                        start=$((start + paused_duration))  # Adjust the end time by adding the paused duration
+                    echo -e "$GREEN Resuming...$FIN"
+                    break
+                fi
+            done
+        fi
         }
     done
 }
 
+
 countdown() {
     time=$1
     session_number=$2
-    start=$(($(date +%s) + $1))
-    if [[ $session_number -ne -1 ]]; then
-        play_music
-    fi
-    display_countdown $start $session_number
+    msg="🍅Time left of session $session_number/$SESSIONS:🍅"
+    [ $session_number -eq -1 ] && msg="🍅Time left of break:🍅"
+
+    # date in seconds when countdown will end
+    start=$(($(date +%s) + $1)); 
+
+    display_countdown $start
     clear
 
     [ $session_number -ne -1 ] && notify-send -t 10000 -u "normal" "Session number $session_number finished"
-
-    if $FIGLET; then
+    
+    # message when session is finished
+    if $FIGLET
+    then
         [ $session_number -ne -1 ] && figlet -c -t "Session $session_number/$SESSIONS finished" || figlet -c -t "Break finished"
     else
-        [ $session_number -ne -1 ] && echo -e "$GREEN Session $session_number/$SESSIONS finished$FIN" || echo -e "$GREEN Break finished$FIN"
+
+        [ $session_number -ne -1 ] && echo -e ""$GREEN"Session $session_number/$SESSIONS finished$FIN" || echo -e "$GREEN""Break finished$FIN"
     fi
 
+    # turn on keypress so we can receive input from user as to when to stop the alarm
     stty echo
     play_alarm "$session_number"
     stty -echo
@@ -191,32 +176,50 @@ countdown() {
     return 0
 }
 
+
 exit_p() {
     write_to_log
+
+    # turn on cursor again
     tput cnorm
+    # turn on keyboard input again
     stty echo
-    echo -e "$RED\nexiting$FIN"
+
+    echo -e ""$RED"\nexiting$FIN"
     exit $1
 }
 
+
 main() {
     find_sound_system
+
+    # when SIGINT is received, exit
     trap "exit_p" 2
+
+    # turn off keyboard input and cursor
     stty -echo
     tput civis
 
+    # convert time and delay to from minutes to seconds
+    # have to divide by 1 to always get integer result
     TIME=$(echo "($TIME * 60)/1" | bc)
     DELAY=$(echo "($DELAY * 60)/1" | bc)
 
-    for ((i = 1; i <= $SESSIONS; i++)); do
+    for ((i = 1; i <= $SESSIONS; i++))
+    do
         clear
+        echo "Time left of session $i/$SESSIONS:"
         countdown $TIME $i
 
-        [ $i -ne $SESSIONS ] && clear && countdown $DELAY -1
+        # don't want to have a break after last session
+        [ $i -ne $SESSIONS ] &&  clear && echo "Time left of break:" && countdown $DELAY -1
     done
 }
 
-while [[ $# -gt 0 ]]; do
+
+# argument handling
+while [[ $# -gt 0 ]]
+do
     case $1 in
         -r)
             total_hours_used
@@ -224,7 +227,7 @@ while [[ $# -gt 0 ]]; do
             ;;
         -t|--time)
             TIME="$2"
-            shift && shift
+            shift && shift # past argument and value
             ;;
         -d|--delay)
             DELAY="$2"
@@ -239,14 +242,17 @@ while [[ $# -gt 0 ]]; do
             shift && shift
             ;;
         -f)
-            if command -v figlet &> /dev/null; then
+            if command -v figlet &> /dev/null
+            then
                 FIGLET=true
             else
                 FIGLET=false
-                echo -e "$RED ERROR$FIN: argument '-f' was given, but figlet is not installed"
+                echo -e ""$RED"ERROR$FIN: argument '-f' was given, but figlet is not installed"
                 echo "Starting without figlet in 3 seconds"
+                # maybe add a keypress to start regardless
                 sleep 3
             fi
+
             shift
             ;;
         -h|--help)
@@ -262,4 +268,3 @@ done
 
 main
 exit_p 0
-
