update

diff --git a/pomodoro/tomatoshell/bin/tomatoshell b/pomodoro/tomatoshell/bin/tomatoshell
--- a/pomodoro/tomatoshell/bin/tomatoshell
+++ b/pomodoro/tomatoshell/bin/tomatoshell
@@ -42,12 +42,10 @@ YELLOW="\033[0;33m"
 CYAN="\033[0;34m"
 FIN="\033[0m"
 
-
 write_to_log() {
     date_f=$(date +"%Y-%m-%d")
     echo "$date_f,$SESSIONS,$TIME" >> "$LOG"
 }
-
 
 total_hours_used() {
     printf "$YELLOW Total time spent focused: $FIN"
@@ -55,95 +53,81 @@ total_hours_used() {
     printf " 🍅🤓\n"
 }
 
-
-# TODO: add option for xdg-open
 find_sound_system() {
-    # added support for pipewire audio player, tested on pop-os (debian)
-    # since, its packed with the OS.
-    if command -v mplayer &> /dev/null
-    then
+    if command -v mplayer &> /dev/null; then
         AUDIO_PLAYER=mplayer
-
-    elif command -v paplay &> /dev/null
-    then
+    elif command -v paplay &> /dev/null; then
         AUDIO_PLAYER=paplay
-    # set AUDIO_PLAYER as pw-play 
-    elif command -v pw-play &> /dev/null
-    then
+    elif command -v pw-play &> /dev/null; then
         AUDIO_PLAYER=pw-play
-
-    elif command -v aplay &> /dev/null
-    then
+    elif command -v aplay &> /dev/null; then
         AUDIO_PLAYER=aplay
-
     else
         AUDIO_PLAYER=0
     fi
 }
 
-
 play_alarm() {
-    # when session is finished, start the alarm
     printf "Press 's' to stop alarm"
     [ $1 -eq -1 ] && echo " and start next session" || echo ""
 
     process_name="tomatoshell_alarm"
 
-    while :
-    do
-        # play alarm sound indefinetely until the 's' key is pressed
-
-        if ! [ -e /proc/"$(pidof "$process_name")"/status ]
-        then
-            # janky :/
+    while :; do
+        if ! [ -e /proc/"$(pidof "$process_name")"/status ]; then
             bash -c "exec -a $process_name $AUDIO_PLAYER $ALARM &>/dev/null" &
         else
             read -t 0.01 -r -s -n 1
             [[ $REPLY == 's' ]] && pkill -f "$process_name" && break
         fi
-    
     done
 }
-
 
 display_countdown() {
     start=$1
+    print_offset=10
 
-    # yeahhhh I don̈́'t know what's going on here either
-    while [ "$start" -ge "$(date +%s)" ]
-    do
-        # due to the rendering of emoji's, the text needs to be offset to appear at the center.
-        # sleeping for one second between each print to stdout uses less cpu power, but will
-        # make the countdown have a discrepency of 1s which is negligable.
-        print_offset=10
-        $FIGLET && clear && printf "%*s\n" $(((${#msg}+$COLUMNS+$print_offset)/2)) "$msg" \
-        && echo -ne "$(date -u --date @$((start - $(date +%s))) +%M:%S)\r" | figlet -c -t ||
-        echo -ne "$CYAN\Uf061 $YELLOW $(date -u --date @$((start - $(date +%s))) +%M:%S)$FIN  🍅\r"
+    while [ "$start" -ge "$(date +%s)" ]; do
+        remaining=$(date -u --date @$((start - $(date +%s))) +%M:%S)
+
+        clear
+
+        lines=$(tput lines)
+        cols=$(tput cols)
+        vertical_padding=$((lines / 2 - 2))
+
+        for ((i=0; i<vertical_padding; i++)); do echo ""; done
+
+        if $FIGLET; then
+            printf "%*s\n" $(((${#msg}+$cols+$print_offset)/2)) "$msg"
+            echo "$remaining" | figlet -c -t
+        else
+            printf "%*s\n" $(((${#msg}+$cols+$print_offset)/2)) "$msg"
+            printf "%*s\r" $(((${#remaining}+$cols+$print_offset)/2)) "$CYAN\Uf061 $YELLOW $remaining$FIN  🍅"
+        fi
 
         read -t 1 -r -s -N 1 && {
-        if [[ $REPLY == 'q' ]]; then
-            exit_p
-        elif [[ $REPLY == 's' ]]; then
-            break
-        elif [[ $REPLY == 'p' ]]; then
-            echo -e "\n$YELLOW Paused... Press p to resume $FIN"
-            local pause_time=$(date +%s)
-            while : ; 
-            do
-                read -r -s -N 1 key
-                if [[ $REPLY == 'p' ]]; then
-                 local resume_time=$(date +%s)  # Get the current time after resuming
-                        local paused_duration=$((resume_time - pause_time))  # Calculate the duration of the pause
-                        start=$((start + paused_duration))  # Adjust the end time by adding the paused duration
-                    echo -e "$GREEN Resuming...$FIN"
-                    break
-                fi
-            done
-        fi
+            if [[ $REPLY == 'q' ]]; then
+                exit_p
+            elif [[ $REPLY == 's' ]]; then
+                break
+            elif [[ $REPLY == 'p' ]]; then
+                echo -e "\n$YELLOW Paused... Press p to resume $FIN"
+                local pause_time=$(date +%s)
+                while :; do
+                    read -r -s -N 1 key
+                    if [[ $REPLY == 'p' ]]; then
+                        local resume_time=$(date +%s)
+                        local paused_duration=$((resume_time - pause_time))
+                        start=$((start + paused_duration))
+                        echo -e "$GREEN Resuming...$FIN"
+                        break
+                    fi
+                done
+            fi
         }
     done
 }
-
 
 countdown() {
     time=$1
@@ -151,24 +135,19 @@ countdown() {
     msg="🍅Time left of session $session_number/$SESSIONS:🍅"
     [ $session_number -eq -1 ] && msg="🍅Time left of break:🍅"
 
-    # date in seconds when countdown will end
-    start=$(($(date +%s) + $1)); 
+    start=$(($(date +%s) + $1))
 
     display_countdown $start
     clear
 
     [ $session_number -ne -1 ] && notify-send -t 10000 -u "normal" "Session number $session_number finished"
-    
-    # message when session is finished
-    if $FIGLET
-    then
+
+    if $FIGLET; then
         [ $session_number -ne -1 ] && figlet -c -t "Session $session_number/$SESSIONS finished" || figlet -c -t "Break finished"
     else
-
-        [ $session_number -ne -1 ] && echo -e ""$GREEN"Session $session_number/$SESSIONS finished$FIN" || echo -e "$GREEN""Break finished$FIN"
+        [ $session_number -ne -1 ] && echo -e "$GREEN Session $session_number/$SESSIONS finished$FIN" || echo -e "$GREEN Break finished$FIN"
     fi
 
-    # turn on keypress so we can receive input from user as to when to stop the alarm
     stty echo
     play_alarm "$session_number"
     stty -echo
@@ -176,50 +155,32 @@ countdown() {
     return 0
 }
 
-
 exit_p() {
     write_to_log
-
-    # turn on cursor again
     tput cnorm
-    # turn on keyboard input again
     stty echo
-
-    echo -e ""$RED"\nexiting$FIN"
+    echo -e "$RED\nexiting$FIN"
     exit $1
 }
 
-
 main() {
     find_sound_system
-
-    # when SIGINT is received, exit
     trap "exit_p" 2
-
-    # turn off keyboard input and cursor
     stty -echo
     tput civis
 
-    # convert time and delay to from minutes to seconds
-    # have to divide by 1 to always get integer result
     TIME=$(echo "($TIME * 60)/1" | bc)
     DELAY=$(echo "($DELAY * 60)/1" | bc)
 
-    for ((i = 1; i <= $SESSIONS; i++))
-    do
+    for ((i = 1; i <= $SESSIONS; i++)); do
         clear
         echo "Time left of session $i/$SESSIONS:"
         countdown $TIME $i
-
-        # don't want to have a break after last session
-        [ $i -ne $SESSIONS ] &&  clear && echo "Time left of break:" && countdown $DELAY -1
+        [ $i -ne $SESSIONS ] && clear && echo "Time left of break:" && countdown $DELAY -1
     done
 }
 
-
-# argument handling
-while [[ $# -gt 0 ]]
-do
+while [[ $# -gt 0 ]]; do
     case $1 in
         -r)
             total_hours_used
@@ -227,7 +188,7 @@ do
             ;;
         -t|--time)
             TIME="$2"
-            shift && shift # past argument and value
+            shift && shift
             ;;
         -d|--delay)
             DELAY="$2"
@@ -242,17 +203,14 @@ do
             shift && shift
             ;;
         -f)
-            if command -v figlet &> /dev/null
-            then
+            if command -v figlet &> /dev/null; then
                 FIGLET=true
             else
                 FIGLET=false
-                echo -e ""$RED"ERROR$FIN: argument '-f' was given, but figlet is not installed"
+                echo -e "$RED ERROR$FIN: argument '-f' was given, but figlet is not installed"
                 echo "Starting without figlet in 3 seconds"
-                # maybe add a keypress to start regardless
                 sleep 3
             fi
-
             shift
             ;;
         -h|--help)
